//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SqlConnection : DbContext
    {
        public SqlConnection()
            : base("name=SqlConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<SubscriptionCompanies> SubscriptionCompanies { get; set; }
        public virtual DbSet<SubscriptionFlights> SubscriptionFlights { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
